name: Automatic sync dev with main

on:
  push:
    branches:
      - development

jobs:
  push-to-main:
    runs-on: ubuntu-latest

    steps:
      - name: List all branches
        run: git branch -a
        
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: development
          fetch-depth: 0

      - name: Push changes to main
        run: |
          git checkout main
          git merge development --no-ff --no-edit
          git push origin main
