name: Automatic sync dev with main

on:
  push:
    branches:
      - development

jobs:
  push-to-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: dev

      - name: Push changes to main
        run: |
          git checkout main
          git merge dev --no-ff --no-edit
          git push origin main
